language: go
sudo: false

go:
- 1.6.3
- 1.7
- 1.8
- 1.9
- 1.10.x

before_script:
- go get -t -v ./...

script:
- go test ./... -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)
