// Code generated by mockery v1.0.0
package mocks

import io "io"
import mock "github.com/stretchr/testify/mock"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Get provides a mock function with given fields: endpoint, headers, auth, body
func (_m *Client) Get(endpoint string, headers map[string]string, auth []string, body io.Reader) ([]byte, int, error) {
	ret := _m.Called(endpoint, headers, auth, body)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string, map[string]string, []string, io.Reader) []byte); ok {
		r0 = rf(endpoint, headers, auth, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(string, map[string]string, []string, io.Reader) int); ok {
		r1 = rf(endpoint, headers, auth, body)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, map[string]string, []string, io.Reader) error); ok {
		r2 = rf(endpoint, headers, auth, body)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Post provides a mock function with given fields: endpoint, headers, auth, body
func (_m *Client) Post(endpoint string, headers map[string]string, auth []string, body io.Reader) ([]byte, int, error) {
	ret := _m.Called(endpoint, headers, auth, body)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string, map[string]string, []string, io.Reader) []byte); ok {
		r0 = rf(endpoint, headers, auth, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(string, map[string]string, []string, io.Reader) int); ok {
		r1 = rf(endpoint, headers, auth, body)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, map[string]string, []string, io.Reader) error); ok {
		r2 = rf(endpoint, headers, auth, body)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Put provides a mock function with given fields: endpoint, headers, auth, body
func (_m *Client) Put(endpoint string, headers map[string]string, auth []string, body io.Reader) ([]byte, int, error) {
	ret := _m.Called(endpoint, headers, auth, body)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string, map[string]string, []string, io.Reader) []byte); ok {
		r0 = rf(endpoint, headers, auth, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(string, map[string]string, []string, io.Reader) int); ok {
		r1 = rf(endpoint, headers, auth, body)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, map[string]string, []string, io.Reader) error); ok {
		r2 = rf(endpoint, headers, auth, body)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
